[package]
name = "thermo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "thermo"
path = "src/main.rs"

[lib]
path = "src/mod.rs"

[dependencies]
csv = "1.3.1"
rand = "0.8.5"
raylib = "5.0.2"
rayon = "1.10.0"
